// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_staking_async`
//!
<<<<<<< HEAD
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `75dbeac523b6`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
=======
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ad005bf13d98`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/asset-hub-westend-runtime/asset_hub_westend_runtime.wasm
// --pallet=pallet_staking_async
// --header=/__w/polkadot-sdk/polkadot-sdk/cumulus/file_header.txt
// --output=./cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_staking_async`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_staking_async::WeightInfo for WeightInfo<T> {
	fn bond() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `6813`
		//  Estimated: `4218`
		// Minimum execution time: 148_479_000 picoseconds.
		Weight::from_parts(154_412_000, 0)
			.saturating_add(Weight::from_parts(0, 4218))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
=======
		//  Measured:  `6793`
		//  Estimated: `0`
		// Minimum execution time: 151_823_000 picoseconds.
		Weight::from_parts(162_698_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn bond_extra() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8274`
		//  Estimated: `8877`
		// Minimum execution time: 8_768_396_000 picoseconds.
		Weight::from_parts(10_330_197_000, 0)
			.saturating_add(Weight::from_parts(0, 8877))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(7))
=======
		//  Measured:  `8254`
		//  Estimated: `0`
		// Minimum execution time: 9_824_370_000 picoseconds.
		Weight::from_parts(13_177_169_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn unbond() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8435`
		//  Estimated: `8877`
		// Minimum execution time: 6_772_963_000 picoseconds.
		Weight::from_parts(8_380_016_000, 0)
			.saturating_add(Weight::from_parts(0, 8877))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().writes(6))
=======
		//  Measured:  `8415`
		//  Estimated: `0`
		// Minimum execution time: 6_984_740_000 picoseconds.
		Weight::from_parts(10_286_473_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn withdraw_unbonded_update() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `7413`
		//  Estimated: `6696`
		// Minimum execution time: 169_983_000 picoseconds.
		Weight::from_parts(174_443_000, 0)
			.saturating_add(Weight::from_parts(0, 6696))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(2))
=======
		//  Measured:  `7393`
		//  Estimated: `0`
		// Minimum execution time: 171_540_000 picoseconds.
		Weight::from_parts(181_106_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn withdraw_unbonded_kill() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8360`
		//  Estimated: `6696`
		// Minimum execution time: 8_213_582_000 picoseconds.
		Weight::from_parts(10_806_637_000, 0)
			.saturating_add(Weight::from_parts(0, 6696))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(12))
=======
		//  Measured:  `8340`
		//  Estimated: `0`
		// Minimum execution time: 10_719_434_000 picoseconds.
		Weight::from_parts(14_830_140_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn validate() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `9905`
		//  Estimated: `4218`
		// Minimum execution time: 157_547_000 picoseconds.
		Weight::from_parts(162_977_000, 0)
			.saturating_add(Weight::from_parts(0, 4218))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(5))
=======
		//  Measured:  `9885`
		//  Estimated: `0`
		// Minimum execution time: 155_256_000 picoseconds.
		Weight::from_parts(161_416_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `k` is `[1, 128]`.
	fn kick(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `12207 + k * (1121 ±0)`
		//  Estimated: `4218 + k * (3033 ±0)`
		// Minimum execution time: 95_868_000 picoseconds.
		Weight::from_parts(85_408_591, 0)
			.saturating_add(Weight::from_parts(0, 4218))
			// Standard Error: 35_128
			.saturating_add(Weight::from_parts(16_893_058, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 3033).saturating_mul(k.into()))
=======
		//  Measured:  `12187 + k * (1121 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 98_146_000 picoseconds.
		Weight::from_parts(145_793_776, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 55_127
			.saturating_add(Weight::from_parts(17_280_864, 0).saturating_mul(k.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `n` is `[1, 16]`.
	fn nominate(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5094 + n * (68 ±0)`
		//  Estimated: `6248 + n * (2520 ±0)`
		// Minimum execution time: 3_915_622_000 picoseconds.
		Weight::from_parts(9_358_633_135, 0)
			.saturating_add(Weight::from_parts(0, 6248))
			// Standard Error: 10_758_800
			.saturating_add(Weight::from_parts(128_769_289, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(Weight::from_parts(0, 2520).saturating_mul(n.into()))
=======
		//  Measured:  `5074 + n * (68 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 3_951_847_000 picoseconds.
		Weight::from_parts(11_093_536_278, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 12_371_015
			.saturating_add(Weight::from_parts(134_071_422, 0).saturating_mul(n.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn chill() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5237`
		//  Estimated: `6248`
		// Minimum execution time: 4_296_652_000 picoseconds.
		Weight::from_parts(5_364_675_000, 0)
			.saturating_add(Weight::from_parts(0, 6248))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
=======
		//  Measured:  `5217`
		//  Estimated: `0`
		// Minimum execution time: 5_461_816_000 picoseconds.
		Weight::from_parts(5_964_595_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn set_payee() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `4060`
		//  Estimated: `4218`
		// Minimum execution time: 58_690_000 picoseconds.
		Weight::from_parts(61_361_000, 0)
			.saturating_add(Weight::from_parts(0, 4218))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
=======
		//  Measured:  `4040`
		//  Estimated: `0`
		// Minimum execution time: 57_034_000 picoseconds.
		Weight::from_parts(61_302_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn update_payee() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5732`
		//  Estimated: `4218`
		// Minimum execution time: 71_527_000 picoseconds.
		Weight::from_parts(74_297_000, 0)
			.saturating_add(Weight::from_parts(0, 4218))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
=======
		//  Measured:  `5712`
		//  Estimated: `0`
		// Minimum execution time: 73_677_000 picoseconds.
		Weight::from_parts(75_535_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn set_controller() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5403`
		//  Estimated: `7446`
		// Minimum execution time: 73_043_000 picoseconds.
		Weight::from_parts(76_801_000, 0)
			.saturating_add(Weight::from_parts(0, 7446))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
=======
		//  Measured:  `5383`
		//  Estimated: `0`
		// Minimum execution time: 73_550_000 picoseconds.
		Weight::from_parts(77_231_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn set_validator_count() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 3_656_000 picoseconds.
		Weight::from_parts(3_972_000, 0)
=======
		// Minimum execution time: 3_820_000 picoseconds.
		Weight::from_parts(4_032_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_no_eras() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 20_178_000 picoseconds.
		Weight::from_parts(21_307_000, 0)
=======
		// Minimum execution time: 20_612_000 picoseconds.
		Weight::from_parts(22_653_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_new_era() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 20_064_000 picoseconds.
		Weight::from_parts(21_212_000, 0)
=======
		// Minimum execution time: 20_353_000 picoseconds.
		Weight::from_parts(21_738_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn force_new_era_always() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 20_256_000 picoseconds.
		Weight::from_parts(21_568_000, 0)
=======
		// Minimum execution time: 20_237_000 picoseconds.
		Weight::from_parts(22_012_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
<<<<<<< HEAD
	/// Storage: `Staking::Invulnerables` (r:0 w:1)
	/// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[0, 20]`.
	fn set_invulnerables(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_855_000 picoseconds.
		Weight::from_parts(4_789_713, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 2_363
			.saturating_add(Weight::from_parts(30_014, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Staking::Ledger` (r:1502 w:1502)
	/// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(753), added: 3228, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Bonded` (r:751 w:751)
	/// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Payee` (r:751 w:0)
	/// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[0, 751]`.
	fn deprecate_controller_batch(u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `195452 + u * (1105 ±0)`
		//  Estimated: `990 + u * (6456 ±0)`
		// Minimum execution time: 6_910_000 picoseconds.
		Weight::from_parts(388_846_959, 0)
			.saturating_add(Weight::from_parts(0, 990))
			// Standard Error: 69_895
			.saturating_add(Weight::from_parts(52_526_808, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(u.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(u.into())))
			.saturating_add(Weight::from_parts(0, 6456).saturating_mul(u.into()))
=======
	/// The range of component `u` is `[0, 751]`.
	fn deprecate_controller_batch(u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `195432 + u * (1105 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 7_164_000 picoseconds.
		Weight::from_parts(223_480_099, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 165_663
			.saturating_add(Weight::from_parts(60_652_060, 0).saturating_mul(u.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn force_unstake() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8305`
		//  Estimated: `6248`
		// Minimum execution time: 9_133_590_000 picoseconds.
		Weight::from_parts(13_013_472_000, 0)
			.saturating_add(Weight::from_parts(0, 6248))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(13))
=======
		//  Measured:  `8285`
		//  Estimated: `0`
		// Minimum execution time: 10_921_590_000 picoseconds.
		Weight::from_parts(16_176_391_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `s` is `[1, 1000]`.
	fn cancel_deferred_slash(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `653`
		//  Estimated: `39479`
		// Minimum execution time: 23_503_000 picoseconds.
		Weight::from_parts(24_702_000, 0)
			.saturating_add(Weight::from_parts(0, 39479))
			// Standard Error: 8_160
			.saturating_add(Weight::from_parts(3_076_280, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
=======
		//  Measured:  `633`
		//  Estimated: `0`
		// Minimum execution time: 21_117_000 picoseconds.
		Weight::from_parts(21_937_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_007
			.saturating_add(Weight::from_parts(3_054_448, 0).saturating_mul(s.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `n` is `[0, 64]`.
	fn payout_stakers_alive_staked(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `33007 + n * (3657 ±0)`
		//  Estimated: `39483 + n * (3228 ±0)`
		// Minimum execution time: 6_926_965_000 picoseconds.
		Weight::from_parts(19_672_312_229, 0)
			.saturating_add(Weight::from_parts(0, 39483))
			// Standard Error: 7_681_540
			.saturating_add(Weight::from_parts(223_887_388, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3228).saturating_mul(n.into()))
=======
		//  Measured:  `32987 + n * (3657 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 6_909_131_000 picoseconds.
		Weight::from_parts(20_652_651_092, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_042_660
			.saturating_add(Weight::from_parts(264_186_902, 0).saturating_mul(n.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `l` is `[1, 32]`.
	fn rebond(_l: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8275 + l * (5 ±0)`
		//  Estimated: `8877`
		// Minimum execution time: 5_894_168_000 picoseconds.
		Weight::from_parts(8_716_404_838, 0)
			.saturating_add(Weight::from_parts(0, 8877))
			// Standard Error: 5_683_036
			.saturating_add(Weight::from_parts(19_865_933, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(6))
=======
		//  Measured:  `8255 + l * (5 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 6_909_067_000 picoseconds.
		Weight::from_parts(10_699_364_610, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn reap_stash() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8368`
		//  Estimated: `6248`
		// Minimum execution time: 9_653_555_000 picoseconds.
		Weight::from_parts(11_371_755_000, 0)
			.saturating_add(Weight::from_parts(0, 6248))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(12))
=======
		//  Measured:  `8348`
		//  Estimated: `0`
		// Minimum execution time: 10_927_055_000 picoseconds.
		Weight::from_parts(13_398_080_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn set_staking_configs_all_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 8_146_000 picoseconds.
		Weight::from_parts(8_904_000, 0)
=======
		// Minimum execution time: 8_168_000 picoseconds.
		Weight::from_parts(8_893_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_staking_configs_all_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 7_192_000 picoseconds.
		Weight::from_parts(7_769_000, 0)
=======
		// Minimum execution time: 7_548_000 picoseconds.
		Weight::from_parts(8_120_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn chill_other() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5360`
		//  Estimated: `6248`
		// Minimum execution time: 7_090_064_000 picoseconds.
		Weight::from_parts(9_174_165_000, 0)
			.saturating_add(Weight::from_parts(0, 6248))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(6))
=======
		//  Measured:  `5350`
		//  Estimated: `0`
		// Minimum execution time: 8_972_274_000 picoseconds.
		Weight::from_parts(12_286_705_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn force_apply_min_commission() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `663`
		//  Estimated: `3510`
		// Minimum execution time: 52_996_000 picoseconds.
		Weight::from_parts(61_427_000, 0)
			.saturating_add(Weight::from_parts(0, 3510))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
=======
		//  Measured:  `640`
		//  Estimated: `0`
		// Minimum execution time: 57_429_000 picoseconds.
		Weight::from_parts(67_310_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn set_min_commission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
<<<<<<< HEAD
		// Minimum execution time: 3_587_000 picoseconds.
		Weight::from_parts(4_080_000, 0)
=======
		// Minimum execution time: 3_827_000 picoseconds.
		Weight::from_parts(4_098_000, 0)
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn restore_ledger() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `6968`
		//  Estimated: `4764`
		// Minimum execution time: 108_119_000 picoseconds.
		Weight::from_parts(112_008_000, 0)
			.saturating_add(Weight::from_parts(0, 4764))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
=======
		//  Measured:  `6948`
		//  Estimated: `0`
		// Minimum execution time: 109_614_000 picoseconds.
		Weight::from_parts(114_855_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn migrate_currency() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `7039`
		//  Estimated: `4764`
		// Minimum execution time: 166_165_000 picoseconds.
		Weight::from_parts(172_969_000, 0)
			.saturating_add(Weight::from_parts(0, 4764))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
=======
		//  Measured:  `7019`
		//  Estimated: `0`
		// Minimum execution time: 162_554_000 picoseconds.
		Weight::from_parts(169_846_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `n` is `[0, 64]`.
	fn apply_slash(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `27546 + n * (2979 ±0)`
		//  Estimated: `39479 + n * (3228 ±0)`
		// Minimum execution time: 6_093_833_000 picoseconds.
		Weight::from_parts(18_285_801_932, 0)
			.saturating_add(Weight::from_parts(0, 39479))
			// Standard Error: 7_041_312
			.saturating_add(Weight::from_parts(206_268_666, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().reads((7_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3228).saturating_mul(n.into()))
=======
		//  Measured:  `27526 + n * (2979 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 7_428_074_000 picoseconds.
		Weight::from_parts(19_830_764_737, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 7_880_082
			.saturating_add(Weight::from_parts(228_874_767, 0).saturating_mul(n.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn process_offence_queue() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `3622`
		//  Estimated: `6617`
		// Minimum execution time: 4_931_437_000 picoseconds.
		Weight::from_parts(11_534_992_000, 0)
			.saturating_add(Weight::from_parts(0, 6617))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Staking::BondedEras` (r:1 w:0)
	/// Proof: `Staking::BondedEras` (`max_values`: Some(1), `max_size`: Some(25), added: 520, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Invulnerables` (r:1 w:0)
	/// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ErasStakersOverview` (r:500 w:0)
	/// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ValidatorSlashInEra` (r:500 w:500)
	/// Proof: `Staking::ValidatorSlashInEra` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OffenceQueue` (r:500 w:500)
	/// Proof: `Staking::OffenceQueue` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `Staking::OffenceQueueEras` (r:1 w:1)
	/// Proof: `Staking::OffenceQueueEras` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[2, 500]`.
	fn rc_on_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `687 + v * (96 ±0)`
		//  Estimated: `2126 + v * (2576 ±0)`
		// Minimum execution time: 3_912_656_000 picoseconds.
		Weight::from_parts(25_718_789_639, 0)
			.saturating_add(Weight::from_parts(0, 2126))
			// Standard Error: 1_422_286
			.saturating_add(Weight::from_parts(56_669_706, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2576).saturating_mul(v.into()))
=======
		//  Measured:  `3602`
		//  Estimated: `0`
		// Minimum execution time: 5_027_278_000 picoseconds.
		Weight::from_parts(12_923_992_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `v` is `[2, 500]`.
	fn rc_on_offence(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `667 + v * (96 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 3_997_424_000 picoseconds.
		Weight::from_parts(28_149_718_556, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 1_586_636
			.saturating_add(Weight::from_parts(57_924_737, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn rc_on_session_report() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `1210`
		//  Estimated: `39483`
		// Minimum execution time: 8_385_725_000 picoseconds.
		Weight::from_parts(10_432_297_000, 0)
			.saturating_add(Weight::from_parts(0, 39483))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(10))
=======
		//  Measured:  `1190`
		//  Estimated: `0`
		// Minimum execution time: 10_892_087_000 picoseconds.
		Weight::from_parts(11_439_807_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `v` is `[1, 1000]`.
	fn prune_era_stakers_paged(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `7932 + v * (3 ±0)`
		//  Estimated: `258685 + v * (4 ±0)`
		// Minimum execution time: 211_105_000 picoseconds.
		Weight::from_parts(253_044_617, 0)
			.saturating_add(Weight::from_parts(0, 258685))
			// Standard Error: 2_328
			.saturating_add(Weight::from_parts(96_252, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(103))
			.saturating_add(T::DbWeight::get().writes(100))
			.saturating_add(Weight::from_parts(0, 4).saturating_mul(v.into()))
=======
		//  Measured:  `7912 + v * (3 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 233_582_000 picoseconds.
		Weight::from_parts(302_127_414, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 3_585
			.saturating_add(Weight::from_parts(83_794, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `v` is `[1, 1000]`.
	fn prune_era_stakers_overview(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `7445`
		//  Estimated: `202035 + v * (83 ±6)`
		// Minimum execution time: 50_603_000 picoseconds.
		Weight::from_parts(244_583_252, 0)
			.saturating_add(Weight::from_parts(0, 202035))
			// Standard Error: 6_711
			.saturating_add(Weight::from_parts(134_813, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(81))
			.saturating_add(T::DbWeight::get().writes(79))
			.saturating_add(Weight::from_parts(0, 83).saturating_mul(v.into()))
=======
		//  Measured:  `7425`
		//  Estimated: `0`
		// Minimum execution time: 57_623_000 picoseconds.
		Weight::from_parts(308_108_210, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 9_129
			.saturating_add(Weight::from_parts(91_683, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `v` is `[1, 1000]`.
	fn prune_era_validator_prefs(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5885`
		//  Estimated: `200831 + v * (83 ±0)`
		// Minimum execution time: 47_487_000 picoseconds.
		Weight::from_parts(243_102_910, 0)
			.saturating_add(Weight::from_parts(0, 200831))
			// Standard Error: 6_618
			.saturating_add(Weight::from_parts(129_797, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(81))
			.saturating_add(T::DbWeight::get().writes(79))
			.saturating_add(Weight::from_parts(0, 83).saturating_mul(v.into()))
=======
		//  Measured:  `5865`
		//  Estimated: `0`
		// Minimum execution time: 53_173_000 picoseconds.
		Weight::from_parts(278_592_462, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_591
			.saturating_add(Weight::from_parts(147_948, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `v` is `[1, 1000]`.
	fn prune_era_claimed_rewards(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `8893`
		//  Estimated: `203169 + v * (84 ±6)`
		// Minimum execution time: 51_670_000 picoseconds.
		Weight::from_parts(256_416_028, 0)
			.saturating_add(Weight::from_parts(0, 203169))
			// Standard Error: 6_969
			.saturating_add(Weight::from_parts(123_988, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(81))
			.saturating_add(T::DbWeight::get().writes(79))
			.saturating_add(Weight::from_parts(0, 84).saturating_mul(v.into()))
=======
		//  Measured:  `8873`
		//  Estimated: `0`
		// Minimum execution time: 55_821_000 picoseconds.
		Weight::from_parts(297_039_564, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 8_692
			.saturating_add(Weight::from_parts(122_602, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn prune_era_validator_reward() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `809`
		//  Estimated: `4274`
		// Minimum execution time: 36_260_000 picoseconds.
		Weight::from_parts(39_183_000, 0)
			.saturating_add(Weight::from_parts(0, 4274))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
=======
		//  Measured:  `789`
		//  Estimated: `0`
		// Minimum execution time: 42_821_000 picoseconds.
		Weight::from_parts(46_037_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn prune_era_reward_points() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `809`
		//  Estimated: `4274`
		// Minimum execution time: 38_554_000 picoseconds.
		Weight::from_parts(43_384_000, 0)
			.saturating_add(Weight::from_parts(0, 4274))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
=======
		//  Measured:  `789`
		//  Estimated: `0`
		// Minimum execution time: 41_525_000 picoseconds.
		Weight::from_parts(46_113_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	fn prune_era_single_entry_cleanups() -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `809`
		//  Estimated: `4274`
		// Minimum execution time: 39_314_000 picoseconds.
		Weight::from_parts(41_058_000, 0)
			.saturating_add(Weight::from_parts(0, 4274))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
=======
		//  Measured:  `789`
		//  Estimated: `0`
		// Minimum execution time: 45_910_000 picoseconds.
		Weight::from_parts(48_324_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
	/// The range of component `v` is `[1, 1000]`.
	fn prune_era_validator_slash_in_era(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
<<<<<<< HEAD
		//  Measured:  `5519 + v * (3 ±0)`
		//  Estimated: `132098 + v * (177 ±0)`
		// Minimum execution time: 58_306_000 picoseconds.
		Weight::from_parts(180_775_367, 0)
			.saturating_add(Weight::from_parts(0, 132098))
			// Standard Error: 7_525
			.saturating_add(Weight::from_parts(220_673, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(49))
			.saturating_add(T::DbWeight::get().writes(48))
			.saturating_add(Weight::from_parts(0, 177).saturating_mul(v.into()))
=======
		//  Measured:  `5499 + v * (3 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 60_851_000 picoseconds.
		Weight::from_parts(210_957_237, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 9_601
			.saturating_add(Weight::from_parts(206_498, 0).saturating_mul(v.into()))
>>>>>>> 822c6f6f ([FRAME] Omni bencher run each benchmark at least 10 secs (#10794))
	}
}
